# Generated by Django 4.1.7 on 2023-03-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldata', '0003_project_code_link_project_img_src_project_site_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='github',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='introductory',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='photo_src',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='site',
            field=models.URLField(default='', max_length=300),
        ),
    ]
