# Generated by Django 4.1.7 on 2023-03-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldata', '0004_aboutme_github_aboutme_introductory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='title_img_src',
            field=models.URLField(default='', max_length=300),
        ),
    ]
