# Generated by Django 4.1.7 on 2023-03-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldata', '0005_aboutme_title_img_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='additional_info',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='additional_info',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='video_link',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='introductory',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='summary',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.CharField(default='', max_length=500),
        ),
    ]
